create table member
(
 no bigint generated by default as identity,
 id varchar(255),
 pw varchar(255),
 name varchar(255),
 email varchar(255),
 gender varchar(255),
 reg_date Date,
 primary key (id)
);